on:
  push:
    branches:
      - main

name: Deploy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    name: Publishes this SST stack

    steps:
      - uses: actions/checkout@v3
      - id: pnpm-install
        uses: mattwyskiel/sst-node-pnpm-setup@v1
      - run: pnpm i
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          role-session-name: whiskey-receipts-service
      - run: pnpm sst deploy --stage prod --outputs-file outputs.json
        env:
          API_CERTIFICATE_ARN: ${{secrets.API_CERTIFICATE_ARN_PROD}}
          API_REGIONAL_DOMAIN_NAME: ${{secrets.API_REGIONAL_DOMAIN_NAME_PROD}}
          API_REGIONAL_HOSTED_ZONE_ID: ${{secrets.API_REGIONAL_HOSTED_ZONE_ID_PROD}}
          API_DOMAIN_NAME: ${{vars.API_DOMAIN_NAME_PROD}}
